---
_process:
    - mode: gate
      when: "{{ protocol_key != 'static static' }}"
static:
    _process:
        - regexp: "(?P<block>ip route (?P<key>\\d+.*\\/\\d+).*)"
          when: "{{ network_instance_key == 'global' }}"
          flat: true
        - regexp: "(?P<block>ip route vrf {{ network_instance_key }} (?P<key>\\d+.*\\/\\d+).*)"
          when: "{{ network_instance_key != 'global' }}"
          flat: true
    config:
        _process: unnecessary
        prefix:
            _process:
                - mode: value
                  value: "{{ static_key }}"
        set-tag:
            _process: not_implemented
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
                - regexp: "(?P<block>ip route (vrf {{ network_instance_key }} )*{{ static_key }} (?P<key>\\d+.\\d+.\\d+.\\d+) (?P<metric>\\d+) tag (?P<tag>\\d+))"
            config:
                _process: unnecessary
                index:
                    _process: not_implemented
                metric:
                    _process:
                        - mode: value
                          value: "{{ extra_vars.metric }}"
                next-hop:
                    _process:
                        - mode: value
                          value: "{{ next_hop_key }}"
                recurse:
                    _process: not_implemented
            index:
                _process: not_implemented
            interface-ref:
                _process: not_implemented
                config:
                    _process: not_implemented
                    interface:
                        _process: not_implemented
                    subinterface:
                        _process: not_implemented
                state:
                    _process: not_implemented
            state:
                _process: not_implemented
    prefix:
        _process: not_implemented
    state:
        _process: not_implemented

