---
metadata:
    processor: XMLParser

vlan:
    _process: unnecessary
    config:
        _process: unnecessary
        vlan-id:
            _process:
                - xpath: "vlan-id"
                  from: "{{ bookmarks['parent'] }}"
