---
metadata:
    processor: XMLParser
    execute:
        - method: _rpc
          kwargs:
              get: "<get-configuration/>"

vlans:
    _process:
        - path: "configuration.vlans"
          from: root_vlans.0
    vlan:
        _process:
            - path: vlan
              key: vlan-id
        config:
            _process: unnecessary
            name:
                _process:
                    - path: name
            status:
                _process:
                    - path: "@inactive"
                      present: no
                      map:
                          true: ACTIVE
                          false: SUSPENDED
            tpid:
                _process: not_implemented
            vlan-id:
                _process:
                    - pre: "{{ vlan_key }}"
        members:
            _process: not_implemented
            member:
                _process: not_implemented
        state:
            _process: not_implemented
        vlan-id:
            _process: unnecessary
